//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HamamatsuCamera {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HamamatsuCamera.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Allocate Buffer..
        /// </summary>
        internal static string MsgBox_Error_AllocateBuffer {
            get {
                return ResourceManager.GetString("MsgBox_Error_AllocateBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in accessing the transfer information of new frame..
        /// </summary>
        internal static string MsgBox_Error_CapTransferInfo {
            get {
                return ResourceManager.GetString("MsgBox_Error_CapTransferInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Disconnect Device..
        /// </summary>
        internal static string MsgBox_Error_CloseDevice {
            get {
                return ResourceManager.GetString("MsgBox_Error_CloseDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Initialize DCAM_API..
        /// </summary>
        internal static string MsgBox_Error_InitAPI {
            get {
                return ResourceManager.GetString("MsgBox_Error_InitAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Load Camera Settings..
        /// </summary>
        internal static string MsgBox_Error_LoadCameraSettings {
            get {
                return ResourceManager.GetString("MsgBox_Error_LoadCameraSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Connect Device..
        /// </summary>
        internal static string MsgBox_Error_OpenDevice {
            get {
                return ResourceManager.GetString("MsgBox_Error_OpenDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Release Buffer..
        /// </summary>
        internal static string MsgBox_Error_ReleaseBuffer {
            get {
                return ResourceManager.GetString("MsgBox_Error_ReleaseBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Start Data Acquistion..
        /// </summary>
        internal static string MsgBox_Error_StartCapture {
            get {
                return ResourceManager.GetString("MsgBox_Error_StartCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Stop Data Acquisition..
        /// </summary>
        internal static string MsgBox_Error_StopCapture {
            get {
                return ResourceManager.GetString("MsgBox_Error_StopCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Deinitialize DCAM_API..
        /// </summary>
        internal static string MsgBox_Error_UnInitAPI {
            get {
                return ResourceManager.GetString("MsgBox_Error_UnInitAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The camera cannot be calibrated while the workflow is running. Please stop the workflow and try again..
        /// </summary>
        internal static string MsgBox_Error_WorkflowRunning {
            get {
                return ResourceManager.GetString("MsgBox_Error_WorkflowRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Input pixel value must be unique..
        /// </summary>
        internal static string MsgBox_Warning_UniqueKey {
            get {
                return ResourceManager.GetString("MsgBox_Warning_UniqueKey", resourceCulture);
            }
        }
    }
}
