using Bonsai.IO;

namespace AllenNeuralDynamics.HamamatsuCamera.Models
{
    /// <summary>
    /// CSV writer properties generated by the <see cref="CsvWriter"/>,
    /// stored in the <see cref="CsvWriterShared"/>,
    /// and used by the <see cref="CsvWriterHelper"/> inside of the <see cref="CameraCapture"/>
    /// </summary>
    internal class CsvWriterProperties
    {
        internal string FileName { get; set; }
        internal PathSuffix Suffix { get; set; }
        internal bool Overwrite { get; set; }
        internal void Clear()
        {
            FileName = string.Empty;
            Suffix = PathSuffix.None;
            Overwrite = false;
        }
    }
}
