using System;

namespace AllenNeuralDynamics.HamamatsuCamera.Models
{
    /// <summary>
    /// Data generated by the processing loop
    /// </summary>
    internal sealed class FramePacket
    {
        // Unmanaged raw pointer
        public IntPtr DataPtr { get; set; }

        // Frame metadata
        public int Left { get; set; }
        public int Top { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int RowBytes { get; set; }
        public ulong FrameIndex { get; set; }              // 64-bit unwrapped frame ID
        public double CameraTimestamp { get; set; }
        public double ComputerTimestamp { get; set; }
        public double ElapsedSeconds { get; set; }          // timestamp since acquisition start
        public int DeinterleaveCount { get; set; }

        // ROI results
        public double[] RoiAverages { get; set; }

        public override string ToString()
        {
            if (RoiAverages == null || RoiAverages.Length == 0)
                return $"{Width},{Height},{Left},{Top},{FrameIndex},{ElapsedSeconds}";

            return $"{Width},{Height},{Left},{Top},{FrameIndex},{ElapsedSeconds},{CameraTimestamp},{ComputerTimestamp},{string.Join(",", RoiAverages)}";
        }
    }
}
