using Bonsai.IO;

namespace AllenNeuralDynamics.HamamatsuCamera.Models
{
    /// <summary>
    /// Tiff writer properties generated by the <see cref="TiffWriter"/>,
    /// stored in the <see cref="TiffWriterShared"/>,
    /// and used by the <see cref="TiffWriterHelper"/> inside of the <see cref="CameraCapture"/>
    /// </summary>
    internal class TiffWriterProperties
    {
        internal string FolderName { get; set; }
        internal string BaseFileName { get; set; }
        internal PathSuffix Suffix { get; set; }
        internal ushort FramesPerTiff { get; set; }
        internal void Clear()
        {
            FolderName = string.Empty;
            BaseFileName = string.Empty;
            Suffix = PathSuffix.None;
            FramesPerTiff = 1000;
        }
    }
}
